workspace:
  base: /go
  path: src/github.com/thejokersthief/go-enc

pipeline:
  run_tests:
    image: golang:${GO_VERSION}
    commands:
      - mkdir -p /go/bin  # Manually ensure the bin directory exists
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  # Install dep
      - /go/bin/dep ensure
      - go test -v enc/*    # Verbose tests
    when:
      event: [push, tag]
  make_package:
    image: golang:${GO_VERSION}
    environment:
      ARTIFACTS: /go/artifacts
    commands:
      - chmod +x .ci/build_arch.bash
      - /bin/bash .ci/build_arch.bash github.com/thejokersthief/go-enc
      - rm -rf ${ARTIFACTS}/.*  # Remove any dotfiles
      - echo "TEST"
      - echo ${ARTIFACTS}
    when:
      event: tag
      matrix:
        GO_VERSION: latest
  upload_package:
    group: release
    image: plugins/s3
    environment:
      ARTIFACTS: /go/artifacts
    secrets:
      - source: ci_obj_location
        target: PLUGIN_ENDPOINT
      - source: ci_obj_access_key
        target: AWS_ACCESS_KEY_ID
      - source: ci_obj_secret_key
        target: AWS_SECRET_ACCESS_KEY
    bucket: go_enc
    strip_prefix: ${ARTIFACTS}/
    source: ${ARTIFACTS}/*
    target: ${TAG}/
    path_style: true
    acl: public-read
    when:
      event: tag
      matrix:
        GO_VERSION: latest
  github_release:
    group: release
    image: plugins/github-release
    environment:
      ARTIFACTS: /go/artifacts
    secrets:
      - source: git_token
        target: github_token
    files: ${ARTIFACTS}/*
    when:
      event: tag
      matrix:
        GO_VERSION: latest

matrix:
  GO_VERSION:
    - latest
    - "1.10"
    - "1.9"
    - "1.8"
    - "1.7"
